#!/bin/sh
#Script by FordSenpai

wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
sleep 2
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 stretch main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
#Requirement
apt update
apt upgrade -y
apt install openvpn nginx php7.0-fpm stunnel4 privoxy squid3 dropbear easy-rsa vnstat ufw build-essential fail2ban zip -y

# initializing var
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
cd /root
wget "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/plugin.tgz"
wget "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/premiummenu.zip"

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6


# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# install webmin
cd
wget "https://raw.githubusercontent.com/Gugun09/premscript/master/webmin_1.801_all.deb"
dpkg --install webmin_1.801_all.deb;
apt-get -y -f install;
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
rm /webmin_1.801_all.deb
service webmin restart

# install screenfetch
cd
wget -O /usr/bin/screenfetch "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/screenfetch"
chmod +x /usr/bin/screenfetch
echo "clear" >> .profile
echo "screenfetch" >> .profile

# install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=442/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells

# install privoxy
cat > /etc/privoxy/config <<-END
user-manual /usr/share/doc/privoxy/user-manual
confdir /etc/privoxy
logdir /var/log/privoxy
filterfile default.filter
logfile logfile
listen-address  0.0.0.0:3356
listen-address  0.0.0.0:8086
toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 1
forwarded-connect-retries  1
accept-intercepted-requests 1
allow-cgi-request-crunching 1
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
permit-access 0.0.0.0/0 xxxxxxxxx
END
sed -i $MYIP2 /etc/privoxy/config;

# install squid3
cat > /etc/squid/squid.conf <<-END
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10
acl SSL_ports port 80-8085
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 444
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/32
acl SSH dst 103.103.0.118-103.103.0.118/32
http_access allow SSH
http_access allow localnet
http_access allow manager localhost
http_access deny manager
http_access allow localhost
http_access deny all
http_port 8085
http_port 3355
coredump_dir /var/spool/squid3
refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320
visible_hostname FordSenpai
END
sed -i $MYIP2 /etc/squid/squid.conf;

# setting banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/johndesu090/AutoScriptDeb8/master/Files/Others/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
service ssh restart
service dropbear restart

# install badvpn
wget -O /usr/bin/badvpn-udpgw "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Plugins/badvpn-udpgw"
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/badvpn-udpgw "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Plugins/badvpn-udpgw64"
fi
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300

#install OpenVPN
cp -r /usr/share/easy-rsa/ /etc/openvpn

##certificates
cacert='-----BEGIN CERTIFICATE-----
MIIFEjCCA/qgAwIBAgIJAON1q7oeL4EzMA0GCSqGSIb3DQEBCwUAMIG2MQswCQYD
VQQGEwJQSDEPMA0GA1UECBMGVGFybGFjMRMwEQYDVQQHEwpDb25jZXBjaW9uMRMw
EQYDVQQKEwpKb2huRm9yZFRWMRMwEQYDVQQLEwpKb2huRm9yZFRWMRYwFAYDVQQD
Ew1Kb2huRm9yZFRWIENBMRswGQYDVQQpExJKb2huRm9yZE1hbmdpbGltYW4xIjAg
BgkqhkiG9w0BCQEWE2FkbWluQGpvaG5mb3JkdHYubWUwHhcNMTkxMTE4MDg0MzUx
WhcNMjkxMTE1MDg0MzUxWjCBtjELMAkGA1UEBhMCUEgxDzANBgNVBAgTBlRhcmxh
YzETMBEGA1UEBxMKQ29uY2VwY2lvbjETMBEGA1UEChMKSm9obkZvcmRUVjETMBEG
A1UECxMKSm9obkZvcmRUVjEWMBQGA1UEAxMNSm9obkZvcmRUViBDQTEbMBkGA1UE
KRMSSm9obkZvcmRNYW5naWxpbWFuMSIwIAYJKoZIhvcNAQkBFhNhZG1pbkBqb2hu
Zm9yZHR2Lm1lMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7Zj5vQRm
7cuYmrQvnpx4Uytw0o1fawlIp1oBL9WWM0QCZQSeYQKxD5UUDyLWCY1YKfXIQWE8
oXA85xNtbRg23/ANfoELwjUbaUe+0N5O1rXfkCwNlZCVzhnAxNXWrnjkFeGaq6Os
M5icMof5kDAKNenZxDvV8P48/iGQvsJbx7etXOP9Ime3b3/85Shn3d7ergyRuxbb
Tborr4LIgPEvdAD5M5mUlUH60r8HPn41qOSVvi/goUoSKwzjFPhnLxa35VoRfL6b
y/AiEHjEC8yFExtlwsxE7/835zVUBjTafGA08Cfx87uGwl2bXenJDnLUc+QlTCoz
ph3MHyLbolcfmwIDAQABo4IBHzCCARswHQYDVR0OBBYEFPjfpsQsM3Mn2z9EaqJQ
b1d/jvHHMIHrBgNVHSMEgeMwgeCAFPjfpsQsM3Mn2z9EaqJQb1d/jvHHoYG8pIG5
MIG2MQswCQYDVQQGEwJQSDEPMA0GA1UECBMGVGFybGFjMRMwEQYDVQQHEwpDb25j
ZXBjaW9uMRMwEQYDVQQKEwpKb2huRm9yZFRWMRMwEQYDVQQLEwpKb2huRm9yZFRW
MRYwFAYDVQQDEw1Kb2huRm9yZFRWIENBMRswGQYDVQQpExJKb2huRm9yZE1hbmdp
bGltYW4xIjAgBgkqhkiG9w0BCQEWE2FkbWluQGpvaG5mb3JkdHYubWWCCQDjdau6
Hi+BMzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBF2BdjoATzKBX9
Q75uMPKpJ1VUWqCip3tknodw4r1lNnK5P5IcPKtkRgqZYaKrLJK7tV3fcfPg1OU0
zhkCQz/IkAWECGFEIY19mvtJpugRBpUZHIYY5Umd3/BXZeLbdOsp20exu4Mcmyxl
VFuR/TqU52bfXE/hWoK1s1Y+BSYW4EVtJpz/6y42NDUoWxGzwWaeH0grAe3fXCH6
+BU8nuzv3NHX7PrWxRwK42hHaLWHdfehQStzuJt8tZW2KqpV+V3quIM/WcEQuRkq
1XLDvTJ+gKLW4+egP0mkN+z3jb/uGqNr37yIBLMZ4HYsOwYCUM1u9buo0kJC4IRs
UzEoT+M8
-----END CERTIFICATE-----';
servercert='Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=PH, ST=Tarlac, L=Concepcion, O=JohnFordTV, OU=JohnFordTV, CN=JohnFordTV CA/name=JohnFordMangiliman/emailAddress=admin@johnfordtv.me
        Validity
            Not Before: Nov 18 08:43:51 2019 GMT
            Not After : Nov 15 08:43:51 2029 GMT
        Subject: C=PH, ST=Tarlac, L=Concepcion, O=JohnFordTV, OU=JohnFordTV, CN=server/name=JohnFordMangiliman/emailAddress=admin@johnfordtv.me
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d4:87:52:75:8a:16:49:20:01:50:98:9c:16:22:
                    85:9b:71:ef:34:ab:f4:f3:cd:dc:0b:ed:ad:95:53:
                    ff:78:d4:85:58:94:7d:2b:92:c7:af:45:6d:29:f9:
                    6e:c1:8f:ae:6e:0e:51:7c:6e:27:78:7c:54:e6:7f:
                    c4:46:4e:bf:6a:a1:e9:0d:58:27:62:7e:dd:c2:c9:
                    0c:a8:52:6e:77:45:07:a2:9a:e4:5e:84:5b:1b:df:
                    29:76:3c:a9:95:66:5f:16:98:d9:f9:46:e7:55:30:
                    18:d2:29:61:cb:28:5d:25:e4:d2:2e:dc:28:8b:8e:
                    97:13:0a:e1:7e:a8:1c:98:2b:53:ae:b5:1a:c0:a1:
                    af:6f:94:ed:9a:e0:2f:7f:ad:8e:37:99:7d:55:da:
                    e0:45:ea:86:6c:eb:d4:c2:bc:f2:f6:b3:67:98:7b:
                    de:aa:76:b3:0e:dd:40:4e:8d:58:5a:fc:71:0b:ed:
                    3b:e8:03:4a:d6:8b:87:3a:ab:f3:11:d4:36:52:23:
                    3d:0b:6e:61:79:ef:e9:5b:46:a7:0d:01:90:24:f8:
                    cf:e4:88:f1:34:f7:b7:4e:41:9c:d9:62:f7:7d:18:
                    ab:11:14:3d:0c:f3:08:64:25:fa:aa:2e:2b:17:16:
                    0d:69:f8:c5:df:ca:71:15:42:00:af:60:09:33:7c:
                    d1:3b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Cert Type: 
                SSL Server
            Netscape Comment: 
                Easy-RSA Generated Server Certificate
            X509v3 Subject Key Identifier: 
                F4:20:25:EE:41:1F:7F:A3:18:31:8A:23:AA:83:7D:4A:28:67:79:25
            X509v3 Authority Key Identifier: 
                keyid:F8:DF:A6:C4:2C:33:73:27:DB:3F:44:6A:A2:50:6F:57:7F:8E:F1:C7
                DirName:/C=PH/ST=Tarlac/L=Concepcion/O=JohnFordTV/OU=JohnFordTV/CN=JohnFordTV CA/name=JohnFordMangiliman/emailAddress=admin@johnfordtv.me
                serial:E3:75:AB:BA:1E:2F:81:33

            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:server
    Signature Algorithm: sha256WithRSAEncryption
         8a:62:ff:e4:bd:2a:c3:0c:59:be:d8:27:f1:25:e0:d0:6f:a9:
         91:fd:00:d5:d5:5f:84:20:59:65:5d:b3:72:66:aa:05:56:ca:
         d3:c6:09:55:c6:c7:9e:b6:fd:aa:d0:83:81:be:60:27:3d:83:
         88:20:28:be:4e:56:a2:73:d6:0d:c7:df:ef:7a:48:b7:54:16:
         c3:15:6c:95:4f:f3:17:0b:80:43:3d:c9:89:aa:83:c4:3b:68:
         92:d2:fa:ad:43:ab:e7:ff:bf:df:61:5f:36:8b:9c:53:96:c5:
         18:db:22:c2:c6:3b:fa:77:4e:10:59:2f:fd:51:22:6c:ed:f6:
         f3:45:fc:ca:b9:06:4f:1c:5f:5b:b1:65:33:49:91:b1:43:c9:
         78:2e:01:de:5e:2c:43:ab:66:9f:c4:cd:73:e0:ac:ef:ff:98:
         c7:75:00:04:ac:da:b7:9b:89:ad:a1:65:1f:03:5e:18:ba:6e:
         7b:af:5e:8b:fa:3a:b1:be:c5:f0:88:bd:0c:5a:dd:c0:17:e9:
         aa:95:37:49:c0:32:44:56:d1:1b:a5:fa:21:e6:5b:4a:0f:2e:
         30:df:98:2a:bb:95:b6:9a:89:ab:c0:bb:78:05:90:85:bd:9c:
         92:d5:c4:f6:bf:4b:d8:35:3c:b7:60:3e:b6:7a:33:ce:94:d8:
         67:29:e0:e8
-----BEGIN CERTIFICATE-----
MIIFfjCCBGagAwIBAgIBATANBgkqhkiG9w0BAQsFADCBtjELMAkGA1UEBhMCUEgx
DzANBgNVBAgTBlRhcmxhYzETMBEGA1UEBxMKQ29uY2VwY2lvbjETMBEGA1UEChMK
Sm9obkZvcmRUVjETMBEGA1UECxMKSm9obkZvcmRUVjEWMBQGA1UEAxMNSm9obkZv
cmRUViBDQTEbMBkGA1UEKRMSSm9obkZvcmRNYW5naWxpbWFuMSIwIAYJKoZIhvcN
AQkBFhNhZG1pbkBqb2huZm9yZHR2Lm1lMB4XDTE5MTExODA4NDM1MVoXDTI5MTEx
NTA4NDM1MVowga8xCzAJBgNVBAYTAlBIMQ8wDQYDVQQIEwZUYXJsYWMxEzARBgNV
BAcTCkNvbmNlcGNpb24xEzARBgNVBAoTCkpvaG5Gb3JkVFYxEzARBgNVBAsTCkpv
aG5Gb3JkVFYxDzANBgNVBAMTBnNlcnZlcjEbMBkGA1UEKRMSSm9obkZvcmRNYW5n
aWxpbWFuMSIwIAYJKoZIhvcNAQkBFhNhZG1pbkBqb2huZm9yZHR2Lm1lMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1IdSdYoWSSABUJicFiKFm3HvNKv0
883cC+2tlVP/eNSFWJR9K5LHr0VtKfluwY+ubg5RfG4neHxU5n/ERk6/aqHpDVgn
Yn7dwskMqFJud0UHoprkXoRbG98pdjyplWZfFpjZ+UbnVTAY0ilhyyhdJeTSLtwo
i46XEwrhfqgcmCtTrrUawKGvb5TtmuAvf62ON5l9VdrgReqGbOvUwrzy9rNnmHve
qnazDt1ATo1YWvxxC+076ANK1ouHOqvzEdQ2UiM9C25hee/pW0anDQGQJPjP5Ijx
NPe3TkGc2WL3fRirERQ9DPMIZCX6qi4rFxYNafjF38pxFUIAr2AJM3zROwIDAQAB
o4IBmjCCAZYwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBkAwNAYJYIZIAYb4
QgENBCcWJUVhc3ktUlNBIEdlbmVyYXRlZCBTZXJ2ZXIgQ2VydGlmaWNhdGUwHQYD
VR0OBBYEFPQgJe5BH3+jGDGKI6qDfUooZ3klMIHrBgNVHSMEgeMwgeCAFPjfpsQs
M3Mn2z9EaqJQb1d/jvHHoYG8pIG5MIG2MQswCQYDVQQGEwJQSDEPMA0GA1UECBMG
VGFybGFjMRMwEQYDVQQHEwpDb25jZXBjaW9uMRMwEQYDVQQKEwpKb2huRm9yZFRW
MRMwEQYDVQQLEwpKb2huRm9yZFRWMRYwFAYDVQQDEw1Kb2huRm9yZFRWIENBMRsw
GQYDVQQpExJKb2huRm9yZE1hbmdpbGltYW4xIjAgBgkqhkiG9w0BCQEWE2FkbWlu
QGpvaG5mb3JkdHYubWWCCQDjdau6Hi+BMzATBgNVHSUEDDAKBggrBgEFBQcDATAL
BgNVHQ8EBAMCBaAwEQYDVR0RBAowCIIGc2VydmVyMA0GCSqGSIb3DQEBCwUAA4IB
AQCKYv/kvSrDDFm+2CfxJeDQb6mR/QDV1V+EIFllXbNyZqoFVsrTxglVxseetv2q
0IOBvmAnPYOIICi+Tlaic9YNx9/veki3VBbDFWyVT/MXC4BDPcmJqoPEO2iS0vqt
Q6vn/7/fYV82i5xTlsUY2yLCxjv6d04QWS/9USJs7fbzRfzKuQZPHF9bsWUzSZGx
Q8l4LgHeXixDq2afxM1z4Kzv/5jHdQAErNq3m4mtoWUfA14Yum57r16L+jqxvsXw
iL0MWt3AF+mqlTdJwDJEVtEbpfoh5ltKDy4w35gqu5W2momrwLt4BZCFvZyS1cT2
v0vYNTy3YD62ejPOlNhnKeDo
-----END CERTIFICATE-----';
serverkey='-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDUh1J1ihZJIAFQ
mJwWIoWbce80q/TzzdwL7a2VU/941IVYlH0rksevRW0p+W7Bj65uDlF8bid4fFTm
f8RGTr9qoekNWCdift3CyQyoUm53RQeimuRehFsb3yl2PKmVZl8WmNn5RudVMBjS
KWHLKF0l5NIu3CiLjpcTCuF+qByYK1OutRrAoa9vlO2a4C9/rY43mX1V2uBF6oZs
69TCvPL2s2eYe96qdrMO3UBOjVha/HEL7TvoA0rWi4c6q/MR1DZSIz0LbmF57+lb
RqcNAZAk+M/kiPE097dOQZzZYvd9GKsRFD0M8whkJfqqLisXFg1p+MXfynEVQgCv
YAkzfNE7AgMBAAECggEBAM+dmopEaVzqLR6k1uYwt0CRXtKfoV2CnxHwEACu3AUX
52QPOvAUJYotUmUMzIu+ZvIQfr4Fhf2HyBCchAsC5q+ul9J3aZIoyU59xSWx0UQm
ZT0N/0XuGmrx6LkerbPLG90hWN7Ryy9HGxhDYMtsFQLts/4fCGS82Qy7NmnapIRp
FeFuNvVrvOoSjQEc9vN6JNoOPIq3fau4P8M1IEWTzjAG2ragDIzMhT9JHchikWzw
xDHMN1aIIxHgGTLZiC6ezTPfaldx9YxF8odW/07VIb7mlZ/rZ361YP1Ke+ejsbiC
AT0VdpG05rIqLA4J4s3G3JBTsLJdeGU1MHL6fRiKVmECgYEA/G4SO6gr4Sf/KS8O
frsO8LbAOtwR0K4c0HXK+CMD1irBkbpqllP591CYRtfSPNj9RQLOvkSDz5B8FIFe
GSqwDuaEJrCSJktfMvSYKvmT+aspsc4RjpC5q2nqpxFMoedB8aa+199k7BTc/BdD
d0+k46SNaRnza6prhGtmELjkG2MCgYEA14jJewscJ77h1TNj//yvFpjN2F9Ukkd6
v9gYcVqeWLyaDfx6XqefgVcQPovJR4K5R41JvEEP2XkmbY3Ht5gVn6oT1p0HQJ59
I9ipCTQ9MbG/nePKqbyXK0U+lnIkc7fYG9tvlm2nu29LbsZEc7jxwfIz9hqYGIMW
UBaKUhmXlkkCgYEAo/2eOsN2PkANtGOttwcvHZKcL6DosflrHsJnqeyVgX0lY9cH
h8HmkpT5WIy9OGp/n2XDijhYqW/kLC4fQ5pH5mY7VCdByz8MCb59XO3nBDv+SlTl
cwjyljmpCABlGIl0fdkmAnhOyFCFgABdBBXpuTod5DnHuhps3womtJZpGqECgYEA
vKsoc2TOSJx240IRD0wJmCY6SmVoioO3l6d5/f/tDJBL6mJQW/svTPEBbz69+rMb
rN6o5Pmu/hdm5A9v++5NP26J3xul9ZLGyFIn5b6ssot9yKBWDy7exSngF6Hi9si/
i+MSUwO6CADsbxNvaD1Eoxl5Er1E1nApYAHbIvL0FsECgYBxVxMV/Cz6CbzVAbHN
5SUDzzRDZEYB80y/yw8s8EAMlu1XEyn7nTV8L7iMwFAgXRyrSLLfPGvtswwiy6/R
9cAevHCAEYmOu9xlv+ibOfPL7n59g82EMWksBQdajjm0ljnCSuEdNiY+6ZSUNHJM
lm3aoyNqAatkKF6U4HXkcMlUjQ==
-----END PRIVATE KEY-----';
dh='-----BEGIN DH PARAMETERS-----
MIGHAoGBAI1BefA3n6IEzNroxC51lbgk3+p08aSccoyBg3wvpf2P8xQLzfH4dJvC
BOkrTgE68VV724bMOxK88k/p41u9+Tjs59ti6pymAvRtETzCYarUzpqvRBtyJNeI
6ZqpFnVsbKoC4NZMIU+f+6Pu5q8v8Yct7OZDEOo3dJQNJLtl3rezAgEC
-----END DH PARAMETERS-----';


cat << END > /etc/openvpn/ca.crt
$cacert
END

cat << END > /etc/openvpn/server.crt
$servercert
END

cat << END > /etc/openvpn/server.key
$serverkey
END

cat << END > /etc/openvpn/dh1024.pem
$dh
END

chmod 755 /etc/openvpn/ca.crt
chmod 644 /etc/openvpn/dh1024.pem
chmod 644 /etc/openvpn/server.crt
chmod 600 /etc/openvpn/server.key
chmod +x /etc/openvpn/ca.crt

# Setting Server
tar -xzvf /root/plugin.tgz -C /usr/lib/openvpn/
chmod +x /usr/lib/openvpn/*
cat > /etc/openvpn/server.conf <<-END
port 110
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh1024.pem
verify-client-cert none
username-as-common-name
plugin /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so login
server 192.168.10.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "route-method exe"
push "route-delay 2"
keepalive 10 120
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
log openvpn.log
verb 3
ncp-disable
cipher none
auth none

END
systemctl start openvpn@server
#Create OpenVPN Config
mkdir -p /home/vps/public_html
cat > /home/vps/public_html/sun-tuctc.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER ""
http-proxy-option CUSTOM-HEADER "POST https://viber.com HTTP/1.0"

END
echo '<ca>' >> /home/vps/public_html/sun-tuctc.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/sun-tuctc.ovpn
echo '</ca>' >> /home/vps/public_html/sun-tuctc.ovpn

cat > /home/vps/public_html/noload.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
persist-key
persist-tun
comp-lzo
bind
float
remote-cert-tls server
verb 3
auth-user-pass
redirect-gateway def1
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/noload.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/noload.ovpn
echo '</ca>' >> /home/vps/public_html/noload.ovpn

cat > /home/vps/public_html/fixplan.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER ""
http-proxy-option CUSTOM-HEADER "POST https://viber.com HTTP/1.1"
http-proxy-option CUSTOM-HEADER "Proxy-Connection: Keep-Alive"

END
echo '<ca>' >> /home/vps/public_html/fixplan.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/fixplan.ovpn
echo '</ca>' >> /home/vps/public_html/fixplan.ovpn

cat > /home/vps/public_html/default.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/default.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/default.ovpn
echo '</ca>' >> /home/vps/public_html/default.ovpn

cat > /home/vps/public_html/tu200.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3355
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER Host line.telegram.me
http-proxy-option CUSTOM-HEADER X-Online-Host line.telegram.me
http-proxy-option CUSTOM-HEADER X-Forward-Host line.telegram.me
http-proxy-option CUSTOM-HEADER Connection Keep-Alive

END
echo '<ca>' >> /home/vps/public_html/tu200.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/tu200.ovpn
echo '</ca>' >> /home/vps/public_html/tu200.ovpn

cat > /home/vps/public_html/gtmfbig.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER "" 
http-proxy-option CUSTOM-HEADER "PUT https://s3.amazonaws.com HTTP/1.1"
http-proxy-option CUSTOM-HEADER Host s3.amazonaws.com
http-proxy-option CUSTOM-HEADER Connection Keep-Alive
http-proxy-option CUSTOM-HEADER Upgrade-Insecure-Requests: 1 

END
echo '<ca>' >> /home/vps/public_html/gtmfbig.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/gtmfbig.ovpn
echo '</ca>' >> /home/vps/public_html/gtmfbig.ovpn

cat > /home/vps/public_html/sunfreeyt.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 8085
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER Host data.iflix.com
http-proxy-option CUSTOM-HEADER X-Online-Host data.iflix.com
http-proxy-option CUSTOM-HEADER X-Forward-Host data.iflix.com
http-proxy-option CUSTOM-HEADER Connection Keep-Alive

END
echo '<ca>' >> /home/vps/public_html/sunfreeyt.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/sunfreeyt.ovpn
echo '</ca>' >> /home/vps/public_html/sunfreeyt.ovpn

cat > /home/vps/public_html/OpenVPN-SSL.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp
remote 127.0.0.1 110
route $MYIP 255.255.255.255 net_gateway
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/OpenVPN-SSL.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/OpenVPN-SSL.ovpn
echo '</ca>' >> /home/vps/public_html/OpenVPN-SSL.ovpn

cat > /home/vps/public_html/JFTV-WG.conf <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
[Interface]
PrivateKey = mP0EfgBeD0vcbx91bNamvsZF8EZkBIasYE3FvuJUw2I=
DNS = 9.9.9.9, 149.112.112.112
Address = 172.16.0.2

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = engage.johnfordtv.ga:2408
END
echo '<ca>' >> /home/vps/public_html/JFTV-WG.conf
cat /etc/openvpn/ca.crt >> /home/vps/public_html/JFTV-WG.conf
echo '</ca>' >> /home/vps/public_html/JFTV-WG.conf

cat > /home/vps/public_html/stunnel.conf <<-END

client = yes
debug = 6

[openvpn]
accept = 127.0.0.1:110
connect = $MYIP:587
TIMEOUTclose = 0
verify = 0
sni = www.viber.com.edgekey.net
END

# Configure Stunnel
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 -subj '/CN=127.0.0.1/O=localhost/C=PH' -keyout /etc/stunnel/stunnel.pem -out /etc/stunnel/stunnel.pem
cat > /etc/stunnel/stunnel.conf <<-END

sslVersion = all
pid = /stunnel.pid
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
client = no

[openvpn]
accept = 587
connect = 127.0.0.1:1147
cert = /etc/stunnel/stunnel.pem

[dropbear]
accept = 444
connect = 127.0.0.1:442
cert = /etc/stunnel/stunnel.pem

END

#Setting UFW
ufw allow ssh
ufw allow 110/tcp
sed -i 's|DEFAULT_INPUT_POLICY="DROP"|DEFAULT_INPUT_POLICY="ACCEPT"|' /etc/default/ufw
sed -i 's|DEFAULT_FORWARD_POLICY="DROP"|DEFAULT_FORWARD_POLICY="ACCEPT"|' /etc/default/ufw

# set ipv4 forward
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i 's|#net.ipv4.ip_forward=1|net.ipv4.ip_forward=1|' /etc/sysctl.conf

#Setting IPtables
cat > /etc/iptables.up.rules <<-END
*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -j SNAT --to-source xxxxxxxxx
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.10.0/24 -o eth0 -j MASQUERADE
COMMIT
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:fail2ban-ssh - [0:0]
-A INPUT -p tcp -m multiport --dports 22 -j fail2ban-ssh
-A INPUT -p ICMP --icmp-type 8 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p tcp --dport 22  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 80  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 143  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 442  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 443  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 444  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 587  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 110  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 110  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 3355  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 3355  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 8085  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 8085  -m state --state NEW -j ACCEPT 
-A INPUT -p tcp --dport 3356  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 3356  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 8086  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 8086  -m state --state NEW -j ACCEPT 
-A INPUT -p tcp --dport 10000  -m state --state NEW -j ACCEPT
-A fail2ban-ssh -j RETURN
COMMIT
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
END
sed -i $MYIP2 /etc/iptables.up.rules;
iptables-restore < /etc/iptables.up.rules

# Configure Nginx
sed -i 's/\/var\/www\/html;/\/home\/vps\/public_html\/;/g' /etc/nginx/sites-enabled/default
cp /var/www/html/index.nginx-debian.html /home/vps/public_html/index.html

#Create Admin
useradd admin
echo "admin:itangsagli" | chpasswd

# Create and Configure rc.local
cat > /etc/rc.local <<-END
#!/bin/sh -e

exit 0
END
chmod +x /etc/rc.local
sed -i '$ i\echo "nameserver 8.8.8.8" > /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 8.8.4.4" >> /etc/resolv.conf' /etc/rc.local
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local

# Configure menu
apt-get install unzip
cd /usr/local/bin/
wget "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Menu/bashmenu.zip" 
unzip bashmenu.zip
chmod +x /usr/local/bin/*

# add eth0 to vnstat
vnstat -u -i eth0

# compress configs
cd /home/vps/public_html
zip configs.zip sun-tuctc.ovpn OpenVPN-SSL.ovpn stunnel.conf fixplan.ovpn noload.ovpn sunfreeyt.ovpn default.ovpn gtmfbig.ovpn tu200.ovpn JFTV-WG.conf

# install libxml-parser
apt-get install libxml-parser-perl -y -f

# finalizing
vnstat -u -i eth0
apt-get -y autoremove
chown -R www-data:www-data /home/vps/public_html
service nginx start
service php7.0-fpm start
service vnstat restart
service openvpn restart
service dropbear restart
service fail2ban restart
service squid restart
service privoxy restart

#clearing history
history -c
rm -rf /root/*
cd /root
# info
clear
echo " "
echo "Installation has been completed!!"
echo " Please Reboot your VPS"
echo "--------------------------- Configuration Setup Server -------------------------"
echo "                            Debian Premium Script                               "
echo "                                 -FordSenpai-                                   "
echo "--------------------------------------------------------------------------------"
echo ""  | tee -a log-install.txt
echo "Server Information"  | tee -a log-install.txt
echo "   - Timezone    : Asia/Manila (GMT +8)"  | tee -a log-install.txt
echo "   - Fail2Ban    : [ON]"  | tee -a log-install.txt
echo "   - IPtables    : [ON]"  | tee -a log-install.txt
echo "   - Auto-Reboot : [OFF]"  | tee -a log-install.txt
echo "   - IPv6        : [OFF]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Application & Port Information"  | tee -a log-install.txt
echo "   - OpenVPN		: TCP 110 "  | tee -a log-install.txt
echo "   - OpenVPN-SSL	: 587 "  | tee -a log-install.txt
echo "   - Dropbear		: 442"  | tee -a log-install.txt
echo "   - Stunnel  	: 444"  | tee -a log-install.txt
echo "   - Squid Proxy	: 3355, 8085 (limit to IP Server)"  | tee -a log-install.txt
echo "   - Privoxy		: 3356, 8086 (limit to IP Server)"  | tee -a log-install.txt
echo "   - BadVPN		: 7300"  | tee -a log-install.txt
echo "   - Nginx		: 80"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Premium Script Information"  | tee -a log-install.txt
echo "   To display list of commands: menu"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Important Information"  | tee -a log-install.txt
echo "   - Download Config OpenVPN : http://$MYIP/configs.zip"  | tee -a log-install.txt
echo "   - Installation Log        : cat /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "   - Webmin                  : http://$MYIP:10000/"  | tee -a log-install.txt
echo ""
echo "------------------------------ Script by FordSenpai -----------------------------"
echo "-----Please Reboot your VPS -----"
sleep 5
