#!/bin/sh
#Script by FordSenpai

wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
sleep 2
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 stretch main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
#Requirement
apt update
apt upgrade -y
apt install openvpn nginx php7.0-fpm stunnel4 privoxy squid3 dropbear easy-rsa vnstat ufw build-essential fail2ban zip -y

# initializing var
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
cd /root
wget "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/plugin.tgz"
wget "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/premiummenu.zip"

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6


# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# install webmin
cd
wget "https://raw.githubusercontent.com/Gugun09/premscript/master/webmin_1.801_all.deb"
dpkg --install webmin_1.801_all.deb;
apt-get -y -f install;
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
rm /webmin_1.801_all.deb
service webmin restart

# install screenfetch
cd
wget -O /usr/bin/screenfetch "https://raw.githubusercontent.com/Gugun09/VPSauto/master/tool/screenfetch"
chmod +x /usr/bin/screenfetch
echo "clear" >> .profile
echo "screenfetch" >> .profile

# install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=442/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells

# install privoxy
cat > /etc/privoxy/config <<-END
user-manual /usr/share/doc/privoxy/user-manual
confdir /etc/privoxy
logdir /var/log/privoxy
filterfile default.filter
logfile logfile
listen-address  0.0.0.0:3356
listen-address  0.0.0.0:8086
toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 1
forwarded-connect-retries  1
accept-intercepted-requests 1
allow-cgi-request-crunching 1
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
permit-access 0.0.0.0/0 xxxxxxxxx
END
sed -i $MYIP2 /etc/privoxy/config;

# install squid3
cat > /etc/squid/squid.conf <<-END
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10
acl SSL_ports port 80-8085
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 444
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/32
acl SSH dst 103.103.0.118-103.103.0.118/32
http_access allow SSH
http_access allow localnet
http_access allow manager localhost
http_access deny manager
http_access allow localhost
http_access deny all
http_port 8085
http_port 3355
coredump_dir /var/spool/squid3
refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320
visible_hostname FordSenpai
END
sed -i $MYIP2 /etc/squid/squid.conf;

# setting banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/johndesu090/AutoScriptDeb8/master/Files/Others/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
service ssh restart
service dropbear restart

# install badvpn
wget -O /usr/bin/badvpn-udpgw "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Plugins/badvpn-udpgw"
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/badvpn-udpgw "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Plugins/badvpn-udpgw64"
fi
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300

#install OpenVPN
cp -r /usr/share/easy-rsa/ /etc/openvpn

##certificates
cacert='-----BEGIN CERTIFICATE-----
MIIDKzCCAhOgAwIBAgIJAPH8h73q8B7uMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCENoYW5nZU1lMB4XDTE4MDgwNTAyMDM0MVoXDTI4MDgwMjAyMDM0MVowEzER
MA8GA1UEAwwIQ2hhbmdlTWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDXHJpDUPRhP1otD6EbgDmTdBZcNsaldgxJ3po+gtrML9lr3u19ieULxH8DQWb8
XeHmc6B4roD3MnogqNSc3GYU8qER1mSzwT5RLLKAj/tViBFdpHqW0ge9PU0F0O51
bvXo+eW31n4lI2Ly2KcYRvnuuEK7p5gd8eY/Lj3QwhNiHiA0dIHkWE6sbKl4INZT
hjEq3md8Bg+X6N1sPkk12x7AlpHKQWnxIMfJyjna3p5WiZSKYRBjnSUVqEOE/pRj
pyyW7F86ZOUkktsTIkdhDeR03HMCoOKLDAMizEwvoO1dUdgTVcuZoKQRcJrKpEIb
A4FfnuFN7Ialr9BjJQ4H+5jZAgMBAAGjgYEwfzAdBgNVHQ4EFgQUHykLbq4y5Cqp
VQ7AcdfcML0l6ZAwQwYDVR0jBDwwOoAUHykLbq4y5CqpVQ7AcdfcML0l6ZChF6QV
MBMxETAPBgNVBAMMCENoYW5nZU1lggkA8fyHverwHu4wDAYDVR0TBAUwAwEB/zAL
BgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAIHTm4MNFXBiw+u8LQtZl9vF
lx4bxWcSG8IgKXK9mLUYOjxzLgxYlmjnEZZNc1ozOQU9vJgUTROOWWSkRDtqJisg
55kYEJxNNwV0ZHeISLqcMVRfWubJXawHSIU8aqjP8HfskMMCTyWOqLVi8IJU0oPa
hfBt/NAeOsO/0IhlNXXOcNXqUA9867G7yO1OXUEecJu6/QE0eJr1e2WY++iNXhVT
W/esomvF2PosIOFFVMnZQ/JD/U17Q3o3+OoP1e7lDwDmsMHCuV0+4jbTTovNf3+f
XHG9NrkRDfCu+F2/+i+hYK4WRY8QF+j9TsMeAddB71DfGEjKlddM9YuxMCIu7yU=
-----END CERTIFICATE-----';
servercert='Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=ChangeMe
        Validity
            Not Before: Aug  5 02:04:05 2018 GMT
            Not After : Aug  2 02:04:05 2028 GMT
        Subject: CN=server
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a8:29:63:b5:8f:0b:a6:3b:f3:f8:63:55:6a:c3:
                    7a:2b:9a:21:34:17:2e:b1:9f:f5:8f:75:55:81:95:
                    e7:49:21:30:88:46:2b:55:4f:73:1f:9e:cf:ec:db:
                    b1:a2:65:0f:7d:72:d2:9c:1f:ef:61:8f:60:eb:66:
                    4b:31:27:9a:f9:19:21:22:68:bf:57:76:e5:5c:39:
                    6d:28:c0:62:e6:8e:85:57:d7:99:17:73:85:ba:34:
                    9d:44:c1:bd:57:e2:df:9e:77:3e:a7:4e:75:66:37:
                    b2:41:5b:5c:49:31:10:c2:80:31:f5:48:1c:3c:d3:
                    e7:03:b6:80:36:95:67:5a:ee:14:1b:3f:85:d7:ba:
                    22:7f:df:ce:04:9f:f6:e1:a9:f7:1d:b2:82:df:de:
                    db:d5:6e:5c:67:55:26:11:29:b0:c2:16:c4:7c:d1:
                    27:d4:65:bd:14:45:6b:33:23:a2:d5:d9:86:fd:38:
                    7b:f2:c3:da:37:9c:3c:07:34:24:e1:2d:b5:2b:1d:
                    1d:a6:17:b5:27:1f:80:91:ef:56:c0:74:91:91:68:
                    c9:9f:51:f6:3b:cc:93:9d:ce:93:ba:c2:49:6c:df:
                    31:fa:41:f2:b9:b4:6c:95:5a:15:34:ae:1b:28:66:
                    49:01:58:b1:23:75:d2:d8:f3:fe:70:29:b7:51:f1:
                    e6:49
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                F9:ED:AA:1F:48:80:88:92:D3:E0:49:5E:A8:7A:05:6A:8D:A9:BF:2F
            X509v3 Authority Key Identifier: 
                keyid:1F:29:0B:6E:AE:32:E4:2A:A9:55:0E:C0:71:D7:DC:30:BD:25:E9:90
                DirName:/CN=ChangeMe
                serial:F1:FC:87:BD:EA:F0:1E:EE

            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
    Signature Algorithm: sha256WithRSAEncryption
         88:e9:51:37:76:f1:28:33:c9:b1:93:6e:78:62:fe:05:24:c5:
         06:a2:e9:1f:a8:24:67:0f:72:8e:45:4c:fe:f2:4e:09:c7:ed:
         cb:13:6c:48:4e:c4:93:34:2f:90:e1:8f:68:bf:83:98:80:19:
         47:1e:03:f6:26:6e:79:cd:3d:8b:b3:04:97:43:65:cd:04:6a:
         4e:84:00:14:4a:91:40:f4:7e:1c:4b:39:c2:cf:c3:a4:e3:17:
         54:84:73:18:31:d7:d9:a0:a8:e9:cf:0c:9d:06:a6:6c:39:74:
         e7:a7:ea:98:d3:42:68:fc:6d:49:aa:a5:80:72:f1:80:bd:9d:
         8f:1e:6a:95:5f:32:7a:c9:45:c7:fb:0b:75:96:77:2a:fb:32:
         ac:e9:3a:ae:49:9f:41:c0:8d:48:35:b6:60:4a:30:69:42:48:
         76:b4:85:d9:4f:76:3e:03:b1:ee:a5:3e:27:d8:de:2d:d7:ce:
         dd:ef:33:f9:8f:0a:09:56:18:22:98:77:f5:84:67:89:25:72:
         77:68:7f:ca:89:48:f6:a5:15:2f:30:59:19:f8:1d:d5:c0:1a:
         91:a2:33:34:c2:49:e8:d7:f0:d0:db:aa:7a:62:12:fc:59:16:
         e6:2f:70:9f:eb:64:31:e0:01:ac:08:2d:6a:74:53:9a:0c:77:
         79:24:d6:04
-----BEGIN CERTIFICATE-----
MIIDNDCCAhygAwIBAgIBATANBgkqhkiG9w0BAQsFADATMREwDwYDVQQDDAhDaGFu
Z2VNZTAeFw0xODA4MDUwMjA0MDVaFw0yODA4MDIwMjA0MDVaMBExDzANBgNVBAMM
BnNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKgpY7WPC6Y7
8/hjVWrDeiuaITQXLrGf9Y91VYGV50khMIhGK1VPcx+ez+zbsaJlD31y0pwf72GP
YOtmSzEnmvkZISJov1d25Vw5bSjAYuaOhVfXmRdzhbo0nUTBvVfi3553PqdOdWY3
skFbXEkxEMKAMfVIHDzT5wO2gDaVZ1ruFBs/hde6In/fzgSf9uGp9x2ygt/e29Vu
XGdVJhEpsMIWxHzRJ9RlvRRFazMjotXZhv04e/LD2jecPAc0JOEttSsdHaYXtScf
gJHvVsB0kZFoyZ9R9jvMk53Ok7rCSWzfMfpB8rm0bJVaFTSuGyhmSQFYsSN10tjz
/nApt1Hx5kkCAwEAAaOBlDCBkTAJBgNVHRMEAjAAMB0GA1UdDgQWBBT57aofSICI
ktPgSV6oegVqjam/LzBDBgNVHSMEPDA6gBQfKQturjLkKqlVDsBx19wwvSXpkKEX
pBUwEzERMA8GA1UEAwwIQ2hhbmdlTWWCCQDx/Ie96vAe7jATBgNVHSUEDDAKBggr
BgEFBQcDATALBgNVHQ8EBAMCBaAwDQYJKoZIhvcNAQELBQADggEBAIjpUTd28Sgz
ybGTbnhi/gUkxQai6R+oJGcPco5FTP7yTgnH7csTbEhOxJM0L5Dhj2i/g5iAGUce
A/YmbnnNPYuzBJdDZc0Eak6EABRKkUD0fhxLOcLPw6TjF1SEcxgx19mgqOnPDJ0G
pmw5dOen6pjTQmj8bUmqpYBy8YC9nY8eapVfMnrJRcf7C3WWdyr7MqzpOq5Jn0HA
jUg1tmBKMGlCSHa0hdlPdj4Dse6lPifY3i3Xzt3vM/mPCglWGCKYd/WEZ4klcndo
f8qJSPalFS8wWRn4HdXAGpGiMzTCSejX8NDbqnpiEvxZFuYvcJ/rZDHgAawILWp0
U5oMd3kk1gQ=
-----END CERTIFICATE-----';
serverkey='-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoKWO1jwumO/P4
Y1Vqw3ormiE0Fy6xn/WPdVWBledJITCIRitVT3Mfns/s27GiZQ99ctKcH+9hj2Dr
ZksxJ5r5GSEiaL9XduVcOW0owGLmjoVX15kXc4W6NJ1Ewb1X4t+edz6nTnVmN7JB
W1xJMRDCgDH1SBw80+cDtoA2lWda7hQbP4XXuiJ/384En/bhqfcdsoLf3tvVblxn
VSYRKbDCFsR80SfUZb0URWszI6LV2Yb9OHvyw9o3nDwHNCThLbUrHR2mF7UnH4CR
71bAdJGRaMmfUfY7zJOdzpO6wkls3zH6QfK5tGyVWhU0rhsoZkkBWLEjddLY8/5w
KbdR8eZJAgMBAAECggEAX+/FB9bFEaCQjnu1RoShFXEIUlyLciDNCnwpPRXVbp41
vvkxTalXB4omG342+Gvpi2tPhmyduC4BYCrq6O8sdcKFackSqIaXUacdhKtFgT18
C2Jf38YzW8kalBhnulUfuJtVLkQPrDJISwshOkx4wE48si/ilD1cRXz/5qQT5AaU
t2SyvzPFGTms3gU2ravYJDSfNOZZMrdilGazV3US9Fc2S2fT5g2jzQxhNzt/BmMD
PD++ZakH20c+PI6iAenuN0ZLeogZS6+CpWe9gqBg/TXqqdcrlXWDWqvX4FmHiRNx
gfArD42uuKJZnYt7/q5npamForgvpT0hIdTjnugrkQKBgQDUprS3CYY0Y508mnHj
tlbTdrD/+viQ7RdI48Hw3o1kFPOMlxOffAU6sgjq2AHSv9HCFZOB/y+1QuUuv97W
6TnMU41c8bfaxN+u+ApO90rFbzo9rMReejn9IhB71d36bRHLfFoWtzOfFxLKxV7i
4Pxr8ZDLr27Cl1oBnTF7kSOPtQKBgQDKcPqeB1LCgleu7xlUqvRyjJsSTnK3OAHP
MJvbdDAIcZvz7HaVJJjHRdrENjVi7tvZQk4JU7FpVYlvH2jehi19yfCCKndk3U+A
uAn/YdEAjLNBOoI3li7US9VM+iDUVQ99ZGcxHLqIv3X27+orSgh9tDVzuVjgAMT6
GWro29UQxQKBgQDREAAU/2EYumKIhVK4y7f69/K2B1g+q0k8GOa/1xzsqwhyTMk2
/2fot8W6lJjeSEWBaVL2+BpAOz80QeBkKzDup6oQGXhmtS0wSJ1h2w+AoYSBxAve
0o2WRtor1SwCGx7mjh/Hu18d5kJMZdSOeyDPQtPW3GepGcGcWp2eXSe4DQKBgFvO
msl59r1BUTSDOFCeatdcDqNhskKHAsMMf1IpwfLCWwBm92wxuZt9gXXEQ7fHLSq9
GBjAvM9RPE+JxgxMe2r1Xr4ZNiYm+3wbemU33gnKxSxKtW0yDbC3Z1dOg/7nSGwM
UYQDTFDhy0Sejurs2ybux+LgZn7HuozVZBeQQnMlAoGBAMxmiLeDvhtQYW3HZlzJ
GhEnsSZgNRT6gBlc2D4PlhUQddFGCYXfbNlo3ZZ3yX7jPnLcKcbWRY4eTmsNkXs3
t0PFP9KIZe27oGvSdFcifoI26qEZ+Y6YdRIrJQTk0vDsLm3y2p5HwGW6nUF6XzrP
TkZfj2PTTWbntmDsBPGWHkV6
-----END PRIVATE KEY-----';
dh='-----BEGIN DH PARAMETERS-----
MIIBCAKCAQEA44IWm/VlsXVi1CS4i5EG2nk/VeboOpr1YW95OV3q5DrgO8yhW5qV
Lvj5AOxdCE4XGGVxy/nzwFz1CEWGcQz4CA3zGnIz18MPoJ6b3tQOxJl3ZY2RWnTa
B7KboBatrd24bnwuoCUgyZw6WLSoGcrGEKV7s5udmMOLCgpM3il3iHQddYdao8WB
0kkICZzX2ADAlZ7dBqk4J/fOuT08FFL/CoBRNBwyWSj0l6IbZewzQg5M4E/PKMlX
gUXvRCKTGR7iRSPUX2N3Qj9DFHHB8o17NDIAbtZh+0XB/5qqdJjkFauzZL+pI4yR
y2yCP/GXcysbdfAwsNdYwK0l6pkwI9vhqwIBAg==
-----END DH PARAMETERS-----';
tlsauth='-----BEGIN OpenVPN Static key V1-----
36d9028268b25cddd03a4d3f2393a446
3498fc4188d5325e05154db94f693430
0231b33e9d3ed233f228bed4b214402e
10142379bbf131d89463a483af99e606
299715748e02f885fc9db0c16a645465
de6bfee7a1ea9950a06df4d8acd33763
c0e8dbf597ffb2fe0f4dc1fef8496307
c3555d4b5009ec7b241fe93d80ac3565
3acb026bc75be18848de1ee24a62cd90
34f1ade3224c69638edc322f8714ef60
01eb9ef38cb6f63d059942e55dbb47fb
8b2286b1fcf8974422fbb047350d76f2
70b4fd3047c9c733cfe9c4ebc891460b
921a8936a6061fb0ce1d269d3ddec1c1
6ba15d4d9b46476071902ed007df1d2b
b6d7ddb5d6a279c82e5bc064a25f0ee2
-----END OpenVPN Static key V1-----';


cat << END > /etc/openvpn/ca.crt
$cacert
END

cat << END > /etc/openvpn/server.crt
$servercert
END

cat << END > /etc/openvpn/server.key
$serverkey
END

cat << END > /etc/openvpn/dh1024.pem
$dh
END

cat << END > /etc/openvpn/ta.key
$tlsauth
END

chmod 755 /etc/openvpn/ca.crt
chmod 644 /etc/openvpn/dh1024.pem
chmod 644 /etc/openvpn/server.crt
chmod 600 /etc/openvpn/server.key
chmod +x /etc/openvpn/ca.crt

# Setting Server
tar -xzvf /root/plugin.tgz -C /usr/lib/openvpn/
chmod +x /usr/lib/openvpn/*
cat > /etc/openvpn/server.conf <<-END
port 110
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh1024.pem
tls-auth ta.key 0
verify-client-cert none
username-as-common-name
plugin /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so login
server 192.168.10.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "route-method exe"
push "route-delay 2"
keepalive 10 120
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
log openvpn.log
verb 3
ncp-disable
cipher none
auth none

END
systemctl start openvpn@server
#Create OpenVPN Config
mkdir -p /home/vps/public_html
cat > /home/vps/public_html/sun-tuctc.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER ""
http-proxy-option CUSTOM-HEADER "POST https://viber.com HTTP/1.0"

END
echo '<ca>' >> /home/vps/public_html/sun-tuctc.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/sun-tuctc.ovpn
echo '</ca>' >> /home/vps/public_html/sun-tuctc.ovpn

cat > /home/vps/public_html/noload.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
persist-key
persist-tun
comp-lzo
bind
float
remote-cert-tls server
verb 3
auth-user-pass
redirect-gateway def1
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/noload.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/noload.ovpn
echo '</ca>' >> /home/vps/public_html/noload.ovpn

cat > /home/vps/public_html/fixplan.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER ""
http-proxy-option CUSTOM-HEADER "POST https://viber.com HTTP/1.1"
http-proxy-option CUSTOM-HEADER "Proxy-Connection: Keep-Alive"

END
echo '<ca>' >> /home/vps/public_html/fixplan.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/fixplan.ovpn
echo '</ca>' >> /home/vps/public_html/fixplan.ovpn

cat > /home/vps/public_html/default.ovpn <<-END
# JohnFordTV's VPN Premium Script
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/default.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/default.ovpn
echo '</ca>' >> /home/vps/public_html/default.ovpn

cat > /home/vps/public_html/tu200.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3355
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER Host line.telegram.me
http-proxy-option CUSTOM-HEADER X-Online-Host line.telegram.me
http-proxy-option CUSTOM-HEADER X-Forward-Host line.telegram.me
http-proxy-option CUSTOM-HEADER Connection Keep-Alive

END
echo '<ca>' >> /home/vps/public_html/tu200.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/tu200.ovpn
echo '</ca>' >> /home/vps/public_html/tu200.ovpn

cat > /home/vps/public_html/gtmfbig.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp-client
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 3356
http-proxy-option CUSTOM-HEADER "" 
http-proxy-option CUSTOM-HEADER "PUT https://s3.amazonaws.com HTTP/1.1"
http-proxy-option CUSTOM-HEADER Host s3.amazonaws.com
http-proxy-option CUSTOM-HEADER Connection Keep-Alive
http-proxy-option CUSTOM-HEADER Upgrade-Insecure-Requests: 1 

END
echo '<ca>' >> /home/vps/public_html/gtmfbig.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/gtmfbig.ovpn
echo '</ca>' >> /home/vps/public_html/gtmfbig.ovpn

cat > /home/vps/public_html/sunfreeyt.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp
remote $MYIP 110
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
http-proxy $MYIP 8085
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER Host data.iflix.com
http-proxy-option CUSTOM-HEADER X-Online-Host data.iflix.com
http-proxy-option CUSTOM-HEADER X-Forward-Host data.iflix.com
http-proxy-option CUSTOM-HEADER Connection Keep-Alive

END
echo '<ca>' >> /home/vps/public_html/sunfreeyt.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/sunfreeyt.ovpn
echo '</ca>' >> /home/vps/public_html/sunfreeyt.ovpn

cat > /home/vps/public_html/OpenVPN-SSL.ovpn <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
auth-user-pass
client
dev tun
proto tcp
remote 127.0.0.1 110
route $MYIP 255.255.255.255 net_gateway
nobind
persist-key
persist-tun
comp-lzo
keepalive 10 120
tls-client
remote-cert-tls server
verb 3
auth-user-pass
cipher none
auth none
auth-nocache
auth-retry interact
connect-retry 0 1
nice -20
reneg-sec 0
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1

END
echo '<ca>' >> /home/vps/public_html/OpenVPN-SSL.ovpn
cat /etc/openvpn/ca.crt >> /home/vps/public_html/OpenVPN-SSL.ovpn
echo '</ca>' >> /home/vps/public_html/OpenVPN-SSL.ovpn

cat > /home/vps/public_html/JFTV-WG.conf <<-END
# JohnFordTV's VPN Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090/AutoScriptDS
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script, Enjoy Highspeed OpenVPN Service
[Interface]
PrivateKey = mP0EfgBeD0vcbx91bNamvsZF8EZkBIasYE3FvuJUw2I=
DNS = 9.9.9.9, 149.112.112.112
Address = 172.16.0.2

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = engage.johnfordtv.ga:2408
END
echo '<ca>' >> /home/vps/public_html/JFTV-WG.conf
cat /etc/openvpn/ca.crt >> /home/vps/public_html/JFTV-WG.conf
echo '</ca>' >> /home/vps/public_html/JFTV-WG.conf

cat > /home/vps/public_html/stunnel.conf <<-END

client = yes
debug = 6

[openvpn]
accept = 127.0.0.1:110
connect = $MYIP:587
TIMEOUTclose = 0
verify = 0
sni = www.viber.com.edgekey.net
END

# Configure Stunnel
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 -subj '/CN=127.0.0.1/O=localhost/C=PH' -keyout /etc/stunnel/stunnel.pem -out /etc/stunnel/stunnel.pem
cat > /etc/stunnel/stunnel.conf <<-END

sslVersion = all
pid = /stunnel.pid
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
client = no

[openvpn]
accept = 587
connect = 127.0.0.1:1147
cert = /etc/stunnel/stunnel.pem

[dropbear]
accept = 444
connect = 127.0.0.1:442
cert = /etc/stunnel/stunnel.pem

END

#Setting UFW
ufw allow ssh
ufw allow 110/tcp
sed -i 's|DEFAULT_INPUT_POLICY="DROP"|DEFAULT_INPUT_POLICY="ACCEPT"|' /etc/default/ufw
sed -i 's|DEFAULT_FORWARD_POLICY="DROP"|DEFAULT_FORWARD_POLICY="ACCEPT"|' /etc/default/ufw

# set ipv4 forward
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i 's|#net.ipv4.ip_forward=1|net.ipv4.ip_forward=1|' /etc/sysctl.conf

#Setting IPtables
cat > /etc/iptables.up.rules <<-END
*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -j SNAT --to-source xxxxxxxxx
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.10.0/24 -o eth0 -j MASQUERADE
COMMIT
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:fail2ban-ssh - [0:0]
-A INPUT -p tcp -m multiport --dports 22 -j fail2ban-ssh
-A INPUT -p ICMP --icmp-type 8 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p tcp --dport 22  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 80  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 143  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 442  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 443  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 444  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 587  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 110  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 110  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 3355  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 3355  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 8085  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 8085  -m state --state NEW -j ACCEPT 
-A INPUT -p tcp --dport 3356  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 3356  -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 8086  -m state --state NEW -j ACCEPT
-A INPUT -p udp --dport 8086  -m state --state NEW -j ACCEPT 
-A INPUT -p tcp --dport 10000  -m state --state NEW -j ACCEPT
-A fail2ban-ssh -j RETURN
COMMIT
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
END
sed -i $MYIP2 /etc/iptables.up.rules;
iptables-restore < /etc/iptables.up.rules

# Configure Nginx
sed -i 's/\/var\/www\/html;/\/home\/vps\/public_html\/;/g' /etc/nginx/sites-enabled/default
cp /var/www/html/index.nginx-debian.html /home/vps/public_html/index.html

#Create Admin
useradd admin
echo "admin:itangsagli" | chpasswd

# Create and Configure rc.local
cat > /etc/rc.local <<-END
#!/bin/sh -e

exit 0
END
chmod +x /etc/rc.local
sed -i '$ i\echo "nameserver 8.8.8.8" > /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 8.8.4.4" >> /etc/resolv.conf' /etc/rc.local
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local

# Configure menu
apt-get install unzip
cd /usr/local/bin/
wget "https://github.com/johndesu090/AutoScriptDebianStretch/raw/master/Files/Menu/bashmenu.zip" 
unzip bashmenu.zip
chmod +x /usr/local/bin/*

# add eth0 to vnstat
vnstat -u -i eth0

# compress configs
cd /home/vps/public_html
zip configs.zip sun-tuctc.ovpn OpenVPN-SSL.ovpn stunnel.conf fixplan.ovpn noload.ovpn sunfreeyt.ovpn default.ovpn gtmfbig.ovpn tu200.ovpn JFTV-WG.conf

# install libxml-parser
apt-get install libxml-parser-perl -y -f

# finalizing
vnstat -u -i eth0
apt-get -y autoremove
chown -R www-data:www-data /home/vps/public_html
service nginx start
service php7.0-fpm start
service vnstat restart
service openvpn restart
service dropbear restart
service fail2ban restart
service squid restart
service privoxy restart

#clearing history
history -c
rm -rf /root/*
cd /root
# info
clear
echo " "
echo "Installation has been completed!!"
echo " Please Reboot your VPS"
echo "--------------------------- Configuration Setup Server -------------------------"
echo "                            Debian Premium Script                               "
echo "                                 -FordSenpai-                                   "
echo "--------------------------------------------------------------------------------"
echo ""  | tee -a log-install.txt
echo "Server Information"  | tee -a log-install.txt
echo "   - Timezone    : Asia/Manila (GMT +8)"  | tee -a log-install.txt
echo "   - Fail2Ban    : [ON]"  | tee -a log-install.txt
echo "   - IPtables    : [ON]"  | tee -a log-install.txt
echo "   - Auto-Reboot : [OFF]"  | tee -a log-install.txt
echo "   - IPv6        : [OFF]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Application & Port Information"  | tee -a log-install.txt
echo "   - OpenVPN		: TCP 110 "  | tee -a log-install.txt
echo "   - OpenVPN-SSL	: 587 "  | tee -a log-install.txt
echo "   - Dropbear		: 442"  | tee -a log-install.txt
echo "   - Stunnel  	: 444"  | tee -a log-install.txt
echo "   - Squid Proxy	: 3355, 8085 (limit to IP Server)"  | tee -a log-install.txt
echo "   - Privoxy		: 3356, 8086 (limit to IP Server)"  | tee -a log-install.txt
echo "   - BadVPN		: 7300"  | tee -a log-install.txt
echo "   - Nginx		: 80"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Premium Script Information"  | tee -a log-install.txt
echo "   To display list of commands: menu"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Important Information"  | tee -a log-install.txt
echo "   - Download Config OpenVPN : http://$MYIP/configs.zip"  | tee -a log-install.txt
echo "   - Installation Log        : cat /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "   - Webmin                  : http://$MYIP:10000/"  | tee -a log-install.txt
echo ""
echo "------------------------------ Script by FordSenpai -----------------------------"
echo "-----Please Reboot your VPS -----"
sleep 5
